openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://api.server.test/v1

components:
  securitySchemes:
    bearerAuth:
      description: "#### Example: Bearer [TOKEN]"
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/login:
    post:
      summary: Login service
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: iroid.test1@gmail.com
                password:
                  type: string
                  minLength: 8
                  example: password
              required:
                - email
                - password
      responses:
        "200":
          description: OK

  /auth/register:
    post:
      summary: Register service
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: iroid.test1@gmail.com
                password:
                  type: string
                  minLength: 8
                  example: password
                confirmPassword:
                  description: This field should equals to `password`
                  type: string
                  minLength: 8
                  example: password
              required:
                - email
                - password
                - confirmPassword

      responses:
        "200":
          description: OK

  /users:
    get:
      description: Get all users
      summary: Get all users
      security:
        - bearerAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
